# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/in_ankith/project/fp_adder_proj/fp_adder_proj.srcs/sources_1/ip/axi_fifo_mm_s_0/axi_fifo_mm_s_0.xci
# IP: The module: 'axi_fifo_mm_s_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/in_ankith/project/fp_adder_proj/fp_adder_proj.srcs/sources_1/ip/axi_fifo_mm_s_0/axi_fifo_mm_s_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_fifo_mm_s_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/in_ankith/project/fp_adder_proj/fp_adder_proj.srcs/sources_1/ip/axi_fifo_mm_s_0/axi_fifo_mm_s_0.xci
# IP: The module: 'axi_fifo_mm_s_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/in_ankith/project/fp_adder_proj/fp_adder_proj.srcs/sources_1/ip/axi_fifo_mm_s_0/axi_fifo_mm_s_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_fifo_mm_s_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
